[project]
name = "uba-mia-vpc3"
version = "0.1.0"
description = "Ambiente de VPC3"
authors = [{ name = "brunomaso1", email = "brunomaso1@hotmail.com" }]
license = { text = "CC" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow (>=11.2.1,<12.0.0)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "triton-windows (<3.4)",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
